version: '3.1'
services:
  db:
    image: mysql
    container_name: pap_test
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - api_data:/var/lib/mysql

volumes:
  api_data: